# frozen_string_literal: true

# AUTO-GENERATED by `rake codegen:key_sizes` from data/oids.yml — DO NOT EDIT.

module PqcAsn1
  module DER
    # Known key sizes (in bytes) for NIST PQC algorithms.
    # Source: FIPS 203 (ML-KEM), FIPS 204 (ML-DSA), FIPS 205 (SLH-DSA).
    KEY_SIZES = {
      OID::ML_DSA_44 => { public: 1312, secret: 2560 }.freeze,
      OID::ML_DSA_65 => { public: 1952, secret: 4032 }.freeze,
      OID::ML_DSA_87 => { public: 2592, secret: 4896 }.freeze,
      OID::ML_KEM_512 => { public: 800, secret: 1632 }.freeze,
      OID::ML_KEM_768 => { public: 1184, secret: 2400 }.freeze,
      OID::ML_KEM_1024 => { public: 1568, secret: 3168 }.freeze,
      OID::SLH_DSA_SHA2_128S => { public: 32, secret: 64 }.freeze,
      OID::SLH_DSA_SHA2_128F => { public: 32, secret: 64 }.freeze,
      OID::SLH_DSA_SHA2_192S => { public: 48, secret: 96 }.freeze,
      OID::SLH_DSA_SHA2_192F => { public: 48, secret: 96 }.freeze,
      OID::SLH_DSA_SHA2_256S => { public: 64, secret: 128 }.freeze,
      OID::SLH_DSA_SHA2_256F => { public: 64, secret: 128 }.freeze,
      OID::SLH_DSA_SHAKE_128S => { public: 32, secret: 64 }.freeze,
      OID::SLH_DSA_SHAKE_128F => { public: 32, secret: 64 }.freeze,
      OID::SLH_DSA_SHAKE_192S => { public: 48, secret: 96 }.freeze,
      OID::SLH_DSA_SHAKE_192F => { public: 48, secret: 96 }.freeze,
      OID::SLH_DSA_SHAKE_256S => { public: 64, secret: 128 }.freeze,
      OID::SLH_DSA_SHAKE_256F => { public: 64, secret: 128 }.freeze,
    }.freeze
  end
end
