/*
 * pqcsb.c — Secure memory buffer for cryptographic key material.
 *
 * GENERATED FILE — do not edit directly.
 * Produced by: scripts/concat.sh
 * Origin: libpqcsb (https://github.com/msuliq/libpqcsb)
 *
 * Standalone C library — no external dependencies beyond the C standard library.
 *
 * To use: include this file in your build along with pqcsb.h and a
 * pqcsb_config.h generated by CMake (or hand-written for your platform).
 */


/* ================================================================== */
/* secure_zero.c */
#include "internal.h"

/* ================================================================== */

/*
 * secure_zero.c — platform-aware secure memory zeroing.
 *
 * Guarantees that the compiler will not optimise away the zeroing, even
 * if the buffer is not read after the call.  Uses the best available
 * primitive on each platform:
 *
 *   1. memset_s      (C11 Annex K — Apple, some BSDs)
 *   2. explicit_bzero (glibc 2.25+, OpenBSD, FreeBSD)
 *   3. SecureZeroMemory (Windows)
 *   4. Volatile loop   (portable fallback)
 */


PQCSB_API void
pqcsb_secure_zero(void *ptr, size_t len)
{
    if (!ptr || len == 0) return;

#if defined(HAVE_MEMSET_S)
    memset_s(ptr, len, 0, len);
#elif defined(HAVE_EXPLICIT_BZERO)
    explicit_bzero(ptr, len);
#elif defined(_WIN32)
    SecureZeroMemory(ptr, len);
#else
    volatile uint8_t *p = (volatile uint8_t *)ptr;
    size_t i;
    for (i = 0; i < len; i++) p[i] = 0;
#endif
}

/* ================================================================== */
/* random.c */
/* ================================================================== */

/*
 * random.c — platform CSPRNG fill.
 *
 * Fills a byte buffer from the best available cryptographic random source:
 *
 *   1. arc4random_buf  (macOS, BSDs — always succeeds, no seeding needed)
 *   2. RtlGenRandom    (Windows — via advapi32, available XP+)
 *   3. getrandom       (Linux 3.17+ — blocks until CSPRNG seeded)
 *   4. getentropy      (glibc 2.25+, OpenBSD, macOS 10.12+ — 256 byte limit)
 *   5. /dev/urandom    (portable fallback — cached fd, never closed)
 *
 * All paths return PQCSB_OK on success or PQCSB_ERR_RANDOM on failure.
 * No Ruby/Python/Rust dependencies.
 */

#include <fcntl.h>
#include <errno.h>

#ifdef HAVE_SYS_RANDOM_H
#include <sys/random.h>
#endif

/* Cached /dev/urandom fd for the fallback path (opened once, never closed).
 * Protected with atomic CAS to avoid race on first initialization. */
#if !defined(HAVE_ARC4RANDOM_BUF) && !defined(HAVE_GETRANDOM) && \
    !defined(HAVE_GETENTROPY) && !defined(_WIN32)
static _Atomic int s_urandom_fd = -1;
#endif

PQCSB_API pqcsb_status_t
pqcsb_fill_random(uint8_t *dst, size_t len)
{
    if (!dst) return PQCSB_ERR_NULL_PARAM;
    if (len == 0) return PQCSB_OK;

#if defined(HAVE_ARC4RANDOM_BUF)
    arc4random_buf(dst, len);
    return PQCSB_OK;

#elif defined(_WIN32)
    if (!RtlGenRandom(dst, (ULONG)len))
        return PQCSB_ERR_RANDOM;
    return PQCSB_OK;

#elif defined(HAVE_GETRANDOM)
    size_t off = 0;
    while (off < len) {
        ssize_t r = getrandom(dst + off, len - off, 0);
        if (r < 0) {
            if (errno == EINTR) continue;
            return PQCSB_ERR_RANDOM;
        }
        off += (size_t)r;
    }
    return PQCSB_OK;

#elif defined(HAVE_GETENTROPY)
    size_t off = 0;
    while (off < len) {
        size_t chunk = len - off;
        if (chunk > 256) chunk = 256;
        if (getentropy(dst + off, chunk) != 0)
            return PQCSB_ERR_RANDOM;
        off += chunk;
    }
    return PQCSB_OK;

#else
    /* Fallback: cached /dev/urandom fd (opened once, never closed).
     * Use atomic CAS to ensure thread-safe initialization. */
    int fd = atomic_load(&s_urandom_fd);
    if (fd < 0) {
        fd = open("/dev/urandom", O_RDONLY | O_CLOEXEC);
        if (fd < 0)
            return PQCSB_ERR_RANDOM;
        int expected = -1;
        if (!atomic_compare_exchange_strong(&s_urandom_fd, &expected, fd)) {
            /* Another thread already initialized it; close our duplicate. */
            close(fd);
            fd = atomic_load(&s_urandom_fd);
        }
    }
    size_t off = 0;
    while (off < len) {
        ssize_t r = read(fd, dst + off, len - off);
        if (r < 0) {
            if (errno == EINTR) continue;
            return PQCSB_ERR_RANDOM;
        }
        if (r == 0)
            return PQCSB_ERR_RANDOM;
        off += (size_t)r;
    }
    return PQCSB_OK;
#endif
}

/* ================================================================== */
/* pqcsb.c */
/* ================================================================== */

/*
 * pqcsb.c — core secure buffer implementation.
 *
 * Layout (mmap path):
 *
 *   [ guard page (PROT_NONE) ][ data region ][ guard page (PROT_NONE) ]
 *                              ^
 *                              | right-aligned within data region:
 *                              | [pad][canary_pre][user_data][canary_post]
 *
 * Right-alignment ensures that overflows from user_data immediately
 * hit the rear guard page, causing a segfault.
 */


/* ------------------------------------------------------------------ */
/* Version                                                             */
/* ------------------------------------------------------------------ */

PQCSB_API const char *
pqcsb_version(void)
{
    return PQCSB_VERSION_STRING;
}

/* ------------------------------------------------------------------ */
/* Error messages and info                                            */
/* ------------------------------------------------------------------ */

PQCSB_API const char *
pqcsb_error_message(pqcsb_status_t code)
{
    switch (code) {
    case PQCSB_OK:             return "success";
    case PQCSB_ERR_ALLOC:      return "memory allocation failed";
    case PQCSB_ERR_MLOCK:      return "mlock failed (buffer still usable)";
    case PQCSB_ERR_MPROTECT:   return "mprotect/VirtualProtect failed";
    case PQCSB_ERR_WIPED:      return "buffer has been wiped";
    case PQCSB_ERR_CANARY:     return "canary corruption detected";
    case PQCSB_ERR_RANDOM:     return "CSPRNG failure";
    case PQCSB_ERR_RANGE:      return "offset/length out of bounds";
    case PQCSB_ERR_NULL_PARAM: return "NULL pointer argument";
    case PQCSB_ERR_BUSY:       return "operation not allowed (buffer in use)";
    }
    return "unknown error";
}

PQCSB_API pqcsb_error_info_t
pqcsb_get_error_info(pqcsb_status_t code)
{
    pqcsb_error_info_t info = { code, 0, 0 };
    switch (code) {
    case PQCSB_OK:             info.is_fatal = 0; info.is_recoverable = 0; break;
    case PQCSB_ERR_ALLOC:      info.is_fatal = 1; info.is_recoverable = 0; break;
    case PQCSB_ERR_MLOCK:      info.is_fatal = 0; info.is_recoverable = 0; break;
    case PQCSB_ERR_MPROTECT:   info.is_fatal = 1; info.is_recoverable = 0; break;
    case PQCSB_ERR_WIPED:      info.is_fatal = 1; info.is_recoverable = 0; break;
    case PQCSB_ERR_CANARY:     info.is_fatal = 1; info.is_recoverable = 0; break;
    case PQCSB_ERR_RANDOM:     info.is_fatal = 0; info.is_recoverable = 1; break;
    case PQCSB_ERR_RANGE:      info.is_fatal = 0; info.is_recoverable = 0; break;
    case PQCSB_ERR_NULL_PARAM: info.is_fatal = 0; info.is_recoverable = 0; break;
    case PQCSB_ERR_BUSY:       info.is_fatal = 0; info.is_recoverable = 0; break;
    }
    return info;
}

PQCSB_API pqcsb_status_t
pqcsb_check_abi_version(int expected_major, int expected_minor)
{
    if (expected_major != PQCSB_ABI_VERSION_MAJOR)
        return PQCSB_ERR_RANGE; /* major version mismatch */
    if (expected_minor > PQCSB_ABI_VERSION_MINOR)
        return PQCSB_ERR_RANGE; /* minor version too new */
    return PQCSB_OK;
}

/* ------------------------------------------------------------------ */
/* Page-size helpers                                                    */
/* ------------------------------------------------------------------ */

static _Atomic size_t s_page_size = 0;

static size_t
page_size(void)
{
    size_t ps = atomic_load(&s_page_size);
    if (ps == 0) {
#ifdef _WIN32
        SYSTEM_INFO si;
        GetSystemInfo(&si);
        ps = (size_t)si.dwPageSize;
        if (ps == 0) ps = 4096;
#else
        long v = sysconf(_SC_PAGESIZE);
        ps = (v > 0) ? (size_t)v : 4096;
#endif
        atomic_store(&s_page_size, ps);
    }
    return ps;
}

static size_t
round_up_page(size_t n)
{
    size_t ps = page_size();
    return (n + ps - 1) & ~(ps - 1);
}

/* ------------------------------------------------------------------ */
/* mlock budget tracking                                               */
/* ------------------------------------------------------------------ */

/* Process-wide counter of mlock'd bytes for RLIMIT_MEMLOCK budgeting. */
static _Atomic size_t s_locked_bytes = 0;

static int
try_mlock(uint8_t *ptr, size_t len)
{
#if defined(HAVE_MLOCK) && defined(HAVE_GETRLIMIT)
    struct rlimit rl;
    if (getrlimit(RLIMIT_MEMLOCK, &rl) != 0) return 0;

    /* Atomically claim the mlock budget before calling mlock to avoid a
     * TOCTOU race where two threads both pass the budget check and then
     * both call mlock, potentially exceeding RLIMIT_MEMLOCK. */
    size_t current = atomic_load(&s_locked_bytes);
    for (;;) {
        size_t needed = current + len;
        if (rl.rlim_cur != RLIM_INFINITY && needed > rl.rlim_cur) return 0;
        if (atomic_compare_exchange_weak(&s_locked_bytes, &current, needed))
            break;
    }

    if (mlock(ptr, len) == 0) {
        return 1;
    }

    /* mlock failed — release the budget we claimed. */
    atomic_fetch_sub(&s_locked_bytes, len);
#elif defined(_WIN32)
    if (VirtualLock(ptr, len)) {
        atomic_fetch_add(&s_locked_bytes, len);
        return 1;
    }
#else
    (void)ptr; (void)len;
#endif
    return 0;
}

static void
do_munlock(uint8_t *ptr, size_t len)
{
#if defined(HAVE_MUNLOCK)
    munlock(ptr, len);
    atomic_fetch_sub(&s_locked_bytes, len);
#elif defined(_WIN32)
    VirtualUnlock(ptr, len);
    atomic_fetch_sub(&s_locked_bytes, len);
#else
    (void)ptr; (void)len;
#endif
}

/* ------------------------------------------------------------------ */
/* mprotect helpers                                                    */
/* ------------------------------------------------------------------ */

static void
protect_none(pqcsb_buf_t *buf)
{
#if PQCSB_HAS_PROTECT
    if (buf->mmap_base && !buf->wiped) {
        size_t ps = page_size();
        PQCSB_SET_PROT(buf->mmap_base, ps, buf->data_pages, PQCSB_PROT_NONE);
    }
#else
    (void)buf;
#endif
}

static void
protect_read(pqcsb_buf_t *buf)
{
#if PQCSB_HAS_PROTECT
    if (buf->mmap_base && !buf->wiped) {
        size_t ps = page_size();
        PQCSB_SET_PROT(buf->mmap_base, ps, buf->data_pages, PQCSB_PROT_READ);
    }
#else
    (void)buf;
#endif
}

static void
protect_rw(pqcsb_buf_t *buf)
{
#if PQCSB_HAS_PROTECT
    if (buf->mmap_base) {
        size_t ps = page_size();
        PQCSB_SET_PROT(buf->mmap_base, ps, buf->data_pages, PQCSB_PROT_RW);
    }
#else
    (void)buf;
#endif
}

/* ------------------------------------------------------------------ */
/* Canary helpers                                                      */
/* ------------------------------------------------------------------ */

static void
write_canaries(pqcsb_buf_t *buf)
{
    memcpy(buf->data - PQCSB_CANARY_SIZE, buf->canary, PQCSB_CANARY_SIZE);
    memcpy(buf->data + buf->len, buf->canary, PQCSB_CANARY_SIZE);
}

static int
check_canaries(const pqcsb_buf_t *buf)
{
    if (memcmp(buf->data - PQCSB_CANARY_SIZE, buf->canary, PQCSB_CANARY_SIZE) != 0)
        return 0;
    if (memcmp(buf->data + buf->len, buf->canary, PQCSB_CANARY_SIZE) != 0)
        return 0;
    return 1;
}

/* ------------------------------------------------------------------ */
/* Buffer allocation / deallocation                                    */
/* ------------------------------------------------------------------ */

static pqcsb_status_t
alloc_buffer(pqcsb_buf_t *buf, size_t len)
{
    pqcsb_status_t rc;

    buf->len        = len;
    buf->wiped      = 0;
    buf->locked     = 0;
    atomic_init(&buf->read_refs, 0);
    buf->mmap_base  = NULL;
    buf->mmap_len   = 0;
    buf->data_pages = 0;

    /* Generate a unique random canary for this buffer.
     * Initialize to zero first to satisfy sanitizers that can't track CSPRNG. */
    memset(buf->canary, 0, PQCSB_CANARY_SIZE);
    rc = pqcsb_fill_random(buf->canary, PQCSB_CANARY_SIZE);
    if (rc != PQCSB_OK) return rc;

#if defined(PQCSB_USE_MMAP)
    size_t ps = page_size();
    size_t needed = PQCSB_CANARY_SIZE + len + PQCSB_CANARY_SIZE;
    size_t data_pages = round_up_page(needed);
    size_t total = ps + data_pages + ps;

    int flags = MAP_PRIVATE | MAP_ANONYMOUS;
#ifdef HAVE_CONST_MAP_NOCORE
    flags |= MAP_NOCORE;
#endif

    uint8_t *base = (uint8_t *)mmap(NULL, total, PROT_READ | PROT_WRITE,
                                     flags, -1, 0);
    if (base == MAP_FAILED)
        return PQCSB_ERR_ALLOC;

    mprotect(base, ps, PROT_NONE);
    mprotect(base + ps + data_pages, ps, PROT_NONE);

#ifdef HAVE_MADVISE
#ifdef HAVE_CONST_MADV_DONTDUMP
    madvise(base + ps, data_pages, MADV_DONTDUMP);
#endif
#ifdef HAVE_CONST_MADV_WIPEONFORK
    madvise(base + ps, data_pages, MADV_WIPEONFORK);
#endif
#endif

    buf->mmap_base  = base;
    buf->mmap_len   = total;
    buf->data_pages = data_pages;

    /* Right-align so overflows immediately hit the rear guard page. */
    buf->data = base + ps + data_pages - PQCSB_CANARY_SIZE - len;
    buf->locked = try_mlock(base + ps, data_pages);

#elif defined(PQCSB_USE_VIRTUALALLOC)
    size_t ps = page_size();
    size_t needed = PQCSB_CANARY_SIZE + len + PQCSB_CANARY_SIZE;
    size_t data_pages = round_up_page(needed);
    size_t total = ps + data_pages + ps;

    uint8_t *base = (uint8_t *)VirtualAlloc(NULL, total,
                                             MEM_COMMIT | MEM_RESERVE,
                                             PAGE_READWRITE);
    if (!base)
        return PQCSB_ERR_ALLOC;

    DWORD old;
    VirtualProtect(base, ps, PAGE_NOACCESS, &old);
    VirtualProtect(base + ps + data_pages, ps, PAGE_NOACCESS, &old);

    buf->mmap_base  = base;
    buf->mmap_len   = total;
    buf->data_pages = data_pages;

    buf->data = base + ps + data_pages - PQCSB_CANARY_SIZE - len;
    buf->locked = try_mlock(base + ps, data_pages);

#else
    /* Fallback: plain malloc with canaries (no guard pages). */
    size_t alloc_size = PQCSB_CANARY_SIZE + len + PQCSB_CANARY_SIZE;
    uint8_t *raw = (uint8_t *)PQCSB_MALLOC(alloc_size);
    if (!raw)
        return PQCSB_ERR_ALLOC;
    buf->data = raw + PQCSB_CANARY_SIZE;
#endif

    return PQCSB_OK;
}

/* ------------------------------------------------------------------ */
/* Lifecycle                                                           */
/* ------------------------------------------------------------------ */

PQCSB_API pqcsb_status_t
pqcsb_create(const uint8_t *data, size_t len, pqcsb_buf_t **out)
{
    return pqcsb_create_ex(data, len, NULL, out);
}

PQCSB_API pqcsb_status_t
pqcsb_create_ex(const uint8_t *data, size_t len,
                const pqcsb_config_t *config,
                pqcsb_buf_t **out)
{
    if (!out) return PQCSB_ERR_NULL_PARAM;
    *out = NULL;
    if (!data) return PQCSB_ERR_NULL_PARAM;
    if (len == 0) return PQCSB_ERR_RANGE;

    pqcsb_buf_t *buf = (pqcsb_buf_t *)PQCSB_MALLOC(sizeof(pqcsb_buf_t));
    if (!buf) return PQCSB_ERR_ALLOC;

    pqcsb_status_t rc = alloc_buffer(buf, len);
    if (rc != PQCSB_OK) {
        PQCSB_FREE(buf);
        return rc;
    }

    /* Initialize configuration (use defaults if none provided). */
    if (config) {
        buf->config = *config;
    } else {
        buf->config = (pqcsb_config_t)PQCSB_CONFIG_DEFAULT;
    }

    memcpy(buf->data, data, len);
    write_canaries(buf);
    protect_none(buf);

    *out = buf;
    return PQCSB_OK;
}

PQCSB_API pqcsb_status_t
pqcsb_create_inplace(size_t len,
                     pqcsb_status_t (*fill)(uint8_t *data, size_t len, void *ctx),
                     void *ctx,
                     pqcsb_buf_t **out)
{
    if (!out) return PQCSB_ERR_NULL_PARAM;
    *out = NULL;
    if (!fill) return PQCSB_ERR_NULL_PARAM;
    if (len == 0) return PQCSB_ERR_RANGE;

    pqcsb_buf_t *buf = (pqcsb_buf_t *)PQCSB_MALLOC(sizeof(pqcsb_buf_t));
    if (!buf) return PQCSB_ERR_ALLOC;

    pqcsb_status_t rc = alloc_buffer(buf, len);
    if (rc != PQCSB_OK) {
        PQCSB_FREE(buf);
        return rc;
    }

    /* Initialize configuration with defaults. */
    buf->config = (pqcsb_config_t)PQCSB_CONFIG_DEFAULT;

    /* Call fill callback — it must return PQCSB_OK. */
    rc = fill(buf->data, len, ctx);
    if (rc != PQCSB_OK) {
        /* Secure zero the region before freeing. */
        protect_rw(buf);
        pqcsb_secure_zero(buf->data - PQCSB_CANARY_SIZE,
                           PQCSB_CANARY_SIZE + len + PQCSB_CANARY_SIZE);
        if (buf->mmap_base) {
#if defined(PQCSB_USE_MMAP)
            munmap(buf->mmap_base, buf->mmap_len);
#elif defined(PQCSB_USE_VIRTUALALLOC)
            VirtualFree(buf->mmap_base, 0, MEM_RELEASE);
#endif
        } else if (buf->data) {
            PQCSB_FREE(buf->data - PQCSB_CANARY_SIZE);
        }
        pqcsb_secure_zero(buf, sizeof(*buf));
        PQCSB_FREE(buf);
        return rc;
    }

    write_canaries(buf);
    protect_none(buf);

    *out = buf;
    return PQCSB_OK;
}

PQCSB_API pqcsb_status_t
pqcsb_create_random(size_t len, pqcsb_buf_t **out)
{
    if (!out) return PQCSB_ERR_NULL_PARAM;
    *out = NULL;
    if (len == 0) return PQCSB_ERR_RANGE;

    pqcsb_buf_t *buf = (pqcsb_buf_t *)PQCSB_MALLOC(sizeof(pqcsb_buf_t));
    if (!buf) return PQCSB_ERR_ALLOC;

    pqcsb_status_t rc = alloc_buffer(buf, len);
    if (rc != PQCSB_OK) {
        PQCSB_FREE(buf);
        return rc;
    }

    /* Initialize configuration with defaults. */
    buf->config = (pqcsb_config_t)PQCSB_CONFIG_DEFAULT;

    rc = pqcsb_fill_random(buf->data, len);
    if (rc != PQCSB_OK) {
        /* Secure zero whatever may have been partially written. */
        pqcsb_secure_zero(buf->data, len);
        if (buf->mmap_base) {
#if defined(PQCSB_USE_MMAP)
            munmap(buf->mmap_base, buf->mmap_len);
#elif defined(PQCSB_USE_VIRTUALALLOC)
            VirtualFree(buf->mmap_base, 0, MEM_RELEASE);
#endif
        } else if (buf->data) {
            PQCSB_FREE(buf->data - PQCSB_CANARY_SIZE);
        }
        pqcsb_secure_zero(buf, sizeof(*buf));
        PQCSB_FREE(buf);
        return rc;
    }

    write_canaries(buf);
    protect_none(buf);

    *out = buf;
    return PQCSB_OK;
}

PQCSB_API pqcsb_status_t
pqcsb_clone(pqcsb_buf_t *src, pqcsb_buf_t **out)
{
    if (!src) return PQCSB_ERR_NULL_PARAM;
    if (src->wiped) return PQCSB_ERR_WIPED;

    pqcsb_read_guard_t guard = pqcsb_begin_read(src);
    if (guard.status != PQCSB_OK)
        return guard.status;

    pqcsb_status_t rc = pqcsb_create(guard.data, guard.len, out);
    pqcsb_end_read(&guard);
    return rc;
}

PQCSB_API void
pqcsb_destroy(pqcsb_buf_t **buf_ptr)
{
    if (!buf_ptr || !*buf_ptr) return;

    pqcsb_buf_t *buf = *buf_ptr;

    /* Wipe if not already wiped. */
    if (!buf->wiped) {
        protect_rw(buf);
        pqcsb_secure_zero(buf->data - PQCSB_CANARY_SIZE,
                           PQCSB_CANARY_SIZE + buf->len + PQCSB_CANARY_SIZE);
        if (buf->locked) {
#if defined(PQCSB_USE_MMAP) || defined(PQCSB_USE_VIRTUALALLOC)
            size_t ps = page_size();
            do_munlock(buf->mmap_base + ps, buf->data_pages);
#endif
        }
    }

    /* Free the mmap/VirtualAlloc/malloc region. */
#if defined(PQCSB_USE_MMAP)
    if (buf->mmap_base) {
        munmap(buf->mmap_base, buf->mmap_len);
    } else if (buf->data) {
        PQCSB_FREE(buf->data - PQCSB_CANARY_SIZE);
    }
#elif defined(PQCSB_USE_VIRTUALALLOC)
    if (buf->mmap_base) {
        VirtualFree(buf->mmap_base, 0, MEM_RELEASE);
    } else if (buf->data) {
        PQCSB_FREE(buf->data - PQCSB_CANARY_SIZE);
    }
#else
    if (buf->data) {
        PQCSB_FREE(buf->data - PQCSB_CANARY_SIZE);
    }
#endif

    /* Zero and free the struct itself. */
    pqcsb_secure_zero(buf, sizeof(*buf));
    PQCSB_FREE(buf);
    *buf_ptr = NULL;
}

/* ------------------------------------------------------------------ */
/* Access control                                                      */
/* ------------------------------------------------------------------ */

PQCSB_API pqcsb_read_guard_t
pqcsb_begin_read(pqcsb_buf_t *buf)
{
    pqcsb_read_guard_t guard = { NULL, 0, PQCSB_OK, NULL };

    if (!buf) {
        guard.status = PQCSB_ERR_NULL_PARAM;
        return guard;
    }
    if (buf->wiped) {
        guard.status = PQCSB_ERR_WIPED;
        return guard;
    }

    /* Only mprotect(PROT_READ) on the first reader; subsequent nested
     * calls just bump the counter. */
    if (atomic_fetch_add(&buf->read_refs, 1) == 0)
        protect_read(buf);

    guard.data = buf->data;
    guard.len = buf->len;
    guard.status = PQCSB_OK;
    guard._priv = buf;
    return guard;
}

PQCSB_API void
pqcsb_end_read(pqcsb_read_guard_t *guard)
{
    if (!guard || !guard->_priv) return;

    pqcsb_buf_t *buf = guard->_priv;
    /* Only re-protect when the last reader exits. */
    if (atomic_fetch_sub(&buf->read_refs, 1) == 1)
        protect_none(buf);

    /* Mark guard as closed. */
    guard->_priv = NULL;
    guard->data = NULL;
    guard->len = 0;
}

PQCSB_API pqcsb_write_guard_t
pqcsb_begin_write(pqcsb_buf_t *buf)
{
    pqcsb_write_guard_t guard = { NULL, 0, PQCSB_OK, NULL };

    if (!buf) {
        guard.status = PQCSB_ERR_NULL_PARAM;
        return guard;
    }
    if (buf->wiped) {
        guard.status = PQCSB_ERR_WIPED;
        return guard;
    }

    protect_rw(buf);

    guard.data = buf->data;
    guard.len = buf->len;
    guard.status = PQCSB_OK;
    guard._priv = buf;
    return guard;
}

PQCSB_API void
pqcsb_end_write(pqcsb_write_guard_t *guard)
{
    if (!guard || !guard->_priv) return;

    pqcsb_buf_t *buf = guard->_priv;
    write_canaries(buf);
    protect_none(buf);

    /* Mark guard as closed. */
    guard->_priv = NULL;
    guard->data = NULL;
    guard->len = 0;
}

/* ------------------------------------------------------------------ */
/* Queries                                                             */
/* ------------------------------------------------------------------ */

PQCSB_API size_t
pqcsb_len(const pqcsb_buf_t *buf)
{
    if (!buf) return 0;
    return buf->len;
}

PQCSB_API int
pqcsb_is_wiped(const pqcsb_buf_t *buf)
{
    if (!buf) return 1;
    return buf->wiped;
}

PQCSB_API int
pqcsb_is_locked(const pqcsb_buf_t *buf)
{
    if (!buf) return 0;
    return buf->locked;
}

PQCSB_API int
pqcsb_is_readable(const pqcsb_buf_t *buf)
{
    if (!buf) return 0;
    return atomic_load(&buf->read_refs) > 0 ? 1 : 0;
}

PQCSB_API int
pqcsb_get_read_refcount(const pqcsb_buf_t *buf)
{
    if (!buf) return 0;
    return (int)atomic_load(&buf->read_refs);
}

PQCSB_API size_t
pqcsb_get_allocation_size(const pqcsb_buf_t *buf)
{
    if (!buf) return 0;
    if (buf->mmap_base) return buf->mmap_len;
    return 0; /* malloc fallback doesn't expose allocation size */
}

/* ------------------------------------------------------------------ */
/* Operations                                                          */
/* ------------------------------------------------------------------ */

PQCSB_API pqcsb_status_t
pqcsb_wipe(pqcsb_buf_t *buf)
{
    if (!buf) return PQCSB_ERR_NULL_PARAM;
    if (buf->wiped) return PQCSB_OK;

    /* Check if buffer is currently held open for reading. */
    if (atomic_load(&buf->read_refs) > 0)
        return PQCSB_ERR_BUSY;

    protect_rw(buf);
    pqcsb_secure_zero(buf->data - PQCSB_CANARY_SIZE,
                       PQCSB_CANARY_SIZE + buf->len + PQCSB_CANARY_SIZE);
    protect_none(buf);

    if (buf->locked) {
#if defined(PQCSB_USE_MMAP) || defined(PQCSB_USE_VIRTUALALLOC)
        size_t ps = page_size();
        do_munlock(buf->mmap_base + ps, buf->data_pages);
#endif
        buf->locked = 0;
    }

    buf->wiped = 1;
    return PQCSB_OK;
}

PQCSB_API pqcsb_status_t
pqcsb_check_canary(pqcsb_buf_t *buf)
{
    if (!buf) return PQCSB_ERR_NULL_PARAM;
    if (buf->wiped) return PQCSB_ERR_WIPED;

    pqcsb_read_guard_t guard = pqcsb_begin_read(buf);
    if (guard.status != PQCSB_OK)
        return guard.status;

    int ok = check_canaries(buf);
    pqcsb_end_read(&guard);

    return ok ? PQCSB_OK : PQCSB_ERR_CANARY;
}

PQCSB_API pqcsb_status_t
pqcsb_slice(pqcsb_buf_t *buf, size_t offset, size_t length,
            pqcsb_buf_t **out)
{
    if (!out) return PQCSB_ERR_NULL_PARAM;
    *out = NULL;
    if (!buf) return PQCSB_ERR_NULL_PARAM;
    if (buf->wiped) return PQCSB_ERR_WIPED;
    if (length == 0) return PQCSB_ERR_RANGE;
    if (offset >= buf->len) return PQCSB_ERR_RANGE;
    if (length > buf->len - offset) return PQCSB_ERR_RANGE;

    pqcsb_read_guard_t guard = pqcsb_begin_read(buf);
    if (guard.status != PQCSB_OK)
        return guard.status;

    pqcsb_status_t rc = pqcsb_create(guard.data + offset, length, out);
    pqcsb_end_read(&guard);

    return rc;
}

PQCSB_API int
pqcsb_ct_equal(pqcsb_buf_t *a, const uint8_t *b, size_t b_len)
{
    if (!a || !b) return 0;
    if (a->wiped) return 0;

    pqcsb_read_guard_t guard = pqcsb_begin_read(a);
    if (guard.status != PQCSB_OK)
        return 0;

    int result;
    if (a->len != b_len) {
        result = 0;
    } else {
        volatile uint8_t diff = 0;
        for (size_t i = 0; i < a->len; i++)
            diff |= guard.data[i] ^ b[i];
        result = (diff == 0) ? 1 : 0;
    }

    pqcsb_end_read(&guard);
    return result;
}

PQCSB_API int
pqcsb_ct_equal_bufs(pqcsb_buf_t *a, pqcsb_buf_t *b)
{
    if (!a || !b) return 0;
    if (a->wiped || b->wiped) return 0;

    pqcsb_read_guard_t guard_a = pqcsb_begin_read(a);
    if (guard_a.status != PQCSB_OK)
        return 0;

    pqcsb_read_guard_t guard_b = pqcsb_begin_read(b);
    if (guard_b.status != PQCSB_OK) {
        pqcsb_end_read(&guard_a);
        return 0;
    }

    int result;
    if (a->len != b->len) {
        result = 0;
    } else {
        volatile uint8_t diff = 0;
        for (size_t i = 0; i < a->len; i++)
            diff |= guard_a.data[i] ^ guard_b.data[i];
        result = (diff == 0) ? 1 : 0;
    }

    pqcsb_end_read(&guard_b);
    pqcsb_end_read(&guard_a);
    return result;
}
