# frozen_string_literal: true

namespace :codegen do
  desc "Regenerate the C key-size table in ext/pqc_asn1/oid.c from data/oids.yml"
  task :oid_c do
    require "yaml"

    data_file = File.expand_path("../data/oids.yml", __dir__)
    oid_c_file = File.expand_path("../ext/pqc_asn1/oid.c", __dir__)

    entries = YAML.load_file(data_file)
    abort "data/oids.yml is empty or invalid" if entries.nil? || entries.empty?

    # Group entries by family for readable comments.
    rows = entries.map do |e|
      %(    {"#{e["dotted"]}", #{e["public_key_size"]}, #{e["secret_key_size"]}},  /* #{e["name"]} */)
    end

    generated = <<~C_ARRAY
      static const oid_size_entry_t OID_KEY_SIZES[] = {
      #{rows.join("\n")}
      };
    C_ARRAY
    generated = generated.rstrip + "\n"

    content = File.read(oid_c_file)
    updated = content.sub(
      /static const oid_size_entry_t OID_KEY_SIZES\[\] = \{.*?\};/m,
      generated.rstrip
    )

    if updated == content
      puts "C table unchanged — data/oids.yml matches ext/pqc_asn1/oid.c."
    else
      File.write(oid_c_file, updated)
      puts "Updated OID_KEY_SIZES in #{oid_c_file} (#{entries.length} entries)."
      puts "Run `bundle exec rake compile` to rebuild the extension."
    end
  end

  desc "Regenerate lib/pqc_asn1/key_sizes.rb from data/oids.yml"
  task :key_sizes do
    require "yaml"

    data_file = File.expand_path("../data/oids.yml", __dir__)
    out_file = File.expand_path("../lib/pqc_asn1/key_sizes.rb", __dir__)

    entries = YAML.load_file(data_file)
    abort "data/oids.yml is empty or invalid" if entries.nil? || entries.empty?

    rows = entries.map do |e|
      "      OID::#{e["name"]} => { public: #{e["public_key_size"]}, secret: #{e["secret_key_size"]} }.freeze,"
    end

    generated = <<~RUBY
      # frozen_string_literal: true

      # AUTO-GENERATED by `rake codegen:key_sizes` from data/oids.yml — DO NOT EDIT.

      module PqcAsn1
        module DER
          # Known key sizes (in bytes) for NIST PQC algorithms.
          # Source: FIPS 203 (ML-KEM), FIPS 204 (ML-DSA), FIPS 205 (SLH-DSA).
          KEY_SIZES = {
      #{rows.join("\n")}
          }.freeze
        end
      end
    RUBY

    File.write(out_file, generated)
    puts "Generated #{out_file} (#{entries.length} entries)."
  end

  desc "Regenerate all codegen targets"
  task all: %i[oid_c key_sizes]
end
