# frozen_string_literal: true

# SHA256 checksums of the currently-vendored individual files.
# Generated by: rake vendor:lock
# Update after every vendor:update run.
VENDOR_FILE_CHECKSUMS = {
  "ext/pqc_asn1/pqc_asn1.h" =>
    "740efc1b6221aa44e05ea02959027fed42b79f257e8efb1c2b88d412c544a0f3",
  "ext/pqc_asn1/pqc_asn1.c" =>
    "fc4d70bd6bac337ce654d885d53e5c88c31abf9712d0143bfcd483bdaef056c7"
}.freeze

# SHA256 checksums for known libpqcasn1 release tarballs.
# Format: version => sha256_of_tar_gz
# Populate after downloading and verifying a release tarball.
VENDOR_CHECKSUMS = {
  "0.1.3" => "sha256:7e44399b0bc6ee1b55c649c0ed63b8450443fe05c49474b29b58a7f5b42f5afa"
}.freeze

namespace :vendor do
  desc "Verify SHA256 of vendored C files against VENDOR_FILE_CHECKSUMS"
  task :verify do
    require "digest"
    ok = true
    VENDOR_FILE_CHECKSUMS.each do |path, expected|
      actual = Digest::SHA256.file(path).hexdigest
      if actual == expected
        puts "  OK  #{path}"
      else
        warn "  FAIL #{path}"
        warn "       expected: #{expected}"
        warn "       actual:   #{actual}"
        ok = false
      end
    end
    abort "Vendored file checksums do not match — run `rake vendor:lock` after intentional updates." unless ok
  end

  desc "Record SHA256 of current vendored C files into VENDOR_FILE_CHECKSUMS"
  task :lock do
    require "digest"
    rake_file = File.expand_path(__FILE__)
    content = File.read(rake_file)

    new_entries = VENDOR_FILE_CHECKSUMS.keys.map { |path|
      sha = Digest::SHA256.file(path).hexdigest
      puts "  #{sha}  #{path}"
      %("#{path}" =>\n    "#{sha}")
    }.join(",\n  ")

    # Replace the VENDOR_FILE_CHECKSUMS block in-place.
    updated = content.sub(
      /VENDOR_FILE_CHECKSUMS = \{.*?\}\.freeze/m,
      "VENDOR_FILE_CHECKSUMS = {\n  #{new_entries}\n}.freeze"
    )

    if updated != content
      File.write(rake_file, updated)
      puts "\nUpdated VENDOR_FILE_CHECKSUMS in #{rake_file}"
    else
      puts "\nChecksums unchanged."
    end
  end

  desc "Regenerate vendored C files from a local libpqcasn1 checkout (dev workflow). " \
       "Set LIBPQCASN1_PATH to the upstream root, or place libpqcasn1 as a sibling directory."
  task :concat do
    require "fileutils"

    upstream = ENV.fetch("LIBPQCASN1_PATH") do
      candidate = File.expand_path("../../libpqcasn1", __dir__)
      abort "libpqcasn1 not found at #{candidate}. Set LIBPQCASN1_PATH env var." unless File.directory?(candidate)
      candidate
    end

    concat_script = File.join(upstream, "scripts/concat.sh")
    abort "concat.sh not found at #{concat_script}" unless File.executable?(concat_script)

    puts "Running concat.sh in #{upstream} ..."
    system("sh", concat_script) || abort("concat.sh failed")

    ext_dir = File.expand_path("ext/pqc_asn1", __dir__ + "/..")

    # Copy the public header verbatim.
    src_h = File.join(upstream, "include/pqc_asn1.h")
    dst_h = File.join(ext_dir, "pqc_asn1.h")
    FileUtils.cp(src_h, dst_h)
    puts "  Copied #{dst_h}"

    # Copy the single-file implementation, replacing the GENERATED header
    # with a VENDORED header so editors know not to edit in-tree.
    src_c = File.join(upstream, "src/pqc_asn1.c")
    content = File.read(src_c)
    vendored_header = <<~HEADER
      /*
       * pqc_asn1.c — DER/PEM/Base64 utilities for post-quantum key serialization.
       *
       * VENDORED FILE — do not edit directly.
       * Origin: libpqcasn1 (https://github.com/msuliq/libpqcasn1)
       * To update: run `bundle exec rake vendor:concat` (local checkout) or
       *            run `bundle exec rake vendor:update[VERSION]` (release tarball).
       *
       * Standalone C library — no external dependencies beyond the C standard library.
       *
       * Algorithm-agnostic codec for ASN.1/DER/PEM/Base64 encoding.
       * All allocating functions use PQC_ASN1_MALLOC / PQC_ASN1_FREE macros
       * (default: malloc/free), configurable by the consumer before including
       * the header.
       *
       * This module is intentionally algorithm-agnostic: the same DER/PEM
       * primitives apply to ML-DSA, ML-KEM, SLH-DSA, and any future PQC
       * scheme that uses standard SPKI / PKCS#8 / PEM wrapping.
       */
    HEADER
    updated = content.sub(/\A\/\*.*?\*\//m, vendored_header.rstrip)
    dst_c = File.join(ext_dir, "pqc_asn1.c")
    File.write(dst_c, updated)
    puts "  Copied #{dst_c}"

    # Write provenance stamp.
    provenance_path = File.join(ext_dir, "VENDOR_PROVENANCE")
    File.write(provenance_path, <<~STAMP)
      upstream: https://github.com/msuliq/libpqcasn1
      source: local checkout (#{upstream})
      vendored_at: #{Time.now.utc.strftime("%Y-%m-%dT%H:%M:%SZ")}
    STAMP
    puts "  Wrote #{provenance_path}"

    Rake::Task[:"vendor:lock"].invoke
    puts "Done. Run `rake test` to verify."
  end

  desc "Update vendored C files from libpqcasn1 GitHub release"
  task :update, [:version] do |_t, args|
    require "net/http"
    require "rubygems/package"
    require "zlib"
    require "stringio"
    require "fileutils"
    require "digest"

    version = args[:version] || abort("Usage: rake vendor:update[VERSION]  (e.g. 0.1.0)")
    tag = "v#{version}"
    prefix = "libpqcasn1-#{version}"
    filename = "#{prefix}.tar.gz"
    url = "https://github.com/msuliq/libpqcasn1/releases/download/#{tag}/#{filename}"

    puts "Downloading #{url} ..."
    uri = URI(url)
    response = Net::HTTP.get_response(uri)
    # Follow one redirect (GitHub releases redirect to S3)
    if response.is_a?(Net::HTTPRedirection)
      response = Net::HTTP.get_response(URI(response["location"]))
    end
    abort "Download failed: #{response.code} #{response.message}" unless response.is_a?(Net::HTTPSuccess)
    tarball = response.body

    # Verify SHA256 against the tarball checksum table if an entry exists.
    actual_sha256 = Digest::SHA256.hexdigest(tarball)
    if (expected = VENDOR_CHECKSUMS[version])
      abort <<~MSG unless actual_sha256 == expected
        SHA256 mismatch for #{filename}!
          expected: #{expected}
          actual:   #{actual_sha256}
        Refusing to update vendored files — the tarball may have been tampered with.
      MSG
      puts "  SHA256 verified: #{actual_sha256}"
    else
      warn <<~MSG
        WARNING: No known SHA256 for libpqcasn1 #{version}.
          Actual SHA256: #{actual_sha256}
        Pin this release by adding to VENDOR_CHECKSUMS in rakelib/vendor.rake:
          "#{version}" => "#{actual_sha256}"
      MSG
    end

    ext_dir = File.expand_path("ext/pqc_asn1", __dir__ + "/..")
    files = {
      "#{prefix}/include/pqc_asn1.h" => File.join(ext_dir, "pqc_asn1.h"),
      "#{prefix}/src/pqc_asn1.c" => File.join(ext_dir, "pqc_asn1.c")
    }

    Gem::Package::TarReader.new(Zlib::GzipReader.new(StringIO.new(tarball))) do |tar|
      tar.each do |entry|
        dest = files[entry.full_name]
        next unless dest

        FileUtils.mkdir_p(File.dirname(dest))
        File.write(dest, entry.read)
        puts "  Updated #{dest}"
        files.delete(entry.full_name)
      end
    end

    files.each_key { |missing| warn "WARNING: #{missing} not found in tarball" }

    # Write a machine-readable provenance stamp so future audits can trace
    # exactly which upstream version is vendored and when it was fetched.
    provenance_path = File.join(ext_dir, "VENDOR_PROVENANCE")
    File.write(provenance_path, <<~STAMP)
      upstream: https://github.com/msuliq/libpqcasn1
      version: #{version}
      tag: #{tag}
      tarball_sha256: #{actual_sha256}
      vendored_at: #{Time.now.utc.strftime("%Y-%m-%dT%H:%M:%SZ")}
    STAMP
    puts "  Wrote #{provenance_path}"

    # Automatically run vendor:lock to record new file checksums.
    puts "\nRecording new file checksums..."
    Rake::Task[:"vendor:lock"].invoke

    puts "Done. Run `rake test` to verify."
  end
end

# SHA256 checksums of the currently-vendored libpqcsb files.
# Generated by: rake vendor_pqcsb:lock
# Update after every vendor_pqcsb:update run.
VENDOR_PQCSB_FILE_CHECKSUMS = {
  "ext/pqc_asn1/pqcsb.h" =>
    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",  # placeholder SHA256
  "ext/pqc_asn1/pqcsb.c" =>
    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",  # placeholder SHA256
  "ext/pqc_asn1/internal.h" =>
    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"   # placeholder SHA256
}.freeze

# SHA256 checksums for known libpqcsb release tarballs.
# Format: version => sha256_of_tar_gz
VENDOR_PQCSB_CHECKSUMS = {}.freeze

namespace :vendor_pqcsb do
  desc "Verify SHA256 of vendored libpqcsb files against VENDOR_PQCSB_FILE_CHECKSUMS"
  task :verify do
    require "digest"
    ok = true
    VENDOR_PQCSB_FILE_CHECKSUMS.each do |path, expected|
      actual = Digest::SHA256.file(path).hexdigest
      if actual == expected
        puts "  OK  #{path}"
      else
        warn "  FAIL #{path}"
        warn "       expected: #{expected}"
        warn "       actual:   #{actual}"
        ok = false
      end
    end
    abort "Vendored libpqcsb file checksums do not match — run `rake vendor_pqcsb:lock` after intentional updates." unless ok
  end

  desc "Record SHA256 of current vendored libpqcsb files into VENDOR_PQCSB_FILE_CHECKSUMS"
  task :lock do
    require "digest"
    rake_file = File.expand_path(__FILE__)
    content = File.read(rake_file)

    new_entries = VENDOR_PQCSB_FILE_CHECKSUMS.keys.map { |path|
      sha = Digest::SHA256.file(path).hexdigest
      puts "  #{sha}  #{path}"
      %("#{path}" =>\n    "#{sha}")
    }.join(",\n  ")

    # Replace the VENDOR_PQCSB_FILE_CHECKSUMS block in-place.
    updated = content.sub(
      /VENDOR_PQCSB_FILE_CHECKSUMS = \{.*?\}\.freeze/m,
      "VENDOR_PQCSB_FILE_CHECKSUMS = {\n  #{new_entries}\n}.freeze"
    )

    if updated != content
      File.write(rake_file, updated)
      puts "\nUpdated VENDOR_PQCSB_FILE_CHECKSUMS in #{rake_file}"
    else
      puts "\nChecksums unchanged."
    end
  end

  desc "Regenerate vendored libpqcsb files from a local checkout (dev workflow). " \
       "Set LIBPQCSB_PATH to the upstream root, or place libpqcsb as a sibling directory."
  task :concat do
    require "fileutils"

    upstream = ENV.fetch("LIBPQCSB_PATH") do
      candidate = File.expand_path("../../libpqcsb", __dir__)
      abort "libpqcsb not found at #{candidate}. Set LIBPQCSB_PATH env var." unless File.directory?(candidate)
      candidate
    end

    concat_script = File.join(upstream, "scripts/concat.sh")
    abort "concat.sh not found at #{concat_script}" unless File.executable?(concat_script)

    puts "Running concat.sh in #{upstream} ..."
    system("sh", concat_script) || abort("concat.sh failed")

    ext_dir = File.expand_path("ext/pqc_asn1", __dir__ + "/..")

    # Copy the public header verbatim.
    src_h = File.join(upstream, "include/pqcsb.h")
    dst_h = File.join(ext_dir, "pqcsb.h")
    FileUtils.cp(src_h, dst_h)
    puts "  Copied #{dst_h}"

    # Copy the single-file implementation verbatim.
    src_c = File.join(upstream, "dist/pqcsb.c")
    dst_c = File.join(ext_dir, "pqcsb.c")
    FileUtils.cp(src_c, dst_c)
    puts "  Copied #{dst_c}"

    # Copy the internal header (private, not installed with libpqcsb).
    src_internal = File.join(upstream, "src/internal.h")
    dst_internal = File.join(ext_dir, "internal.h")
    FileUtils.cp(src_internal, dst_internal)
    puts "  Copied #{dst_internal}"

    # Write provenance stamp.
    provenance_path = File.join(ext_dir, "VENDOR_PROVENANCE")
    existing = File.exist?(provenance_path) ? File.read(provenance_path) : ""
    pqcsb_provenance = <<~STAMP
      ## libpqcsb

      upstream: https://github.com/msuliq/libpqcsb
      source: local checkout (#{upstream})
      vendored_at: #{Time.now.utc.strftime("%Y-%m-%dT%H:%M:%SZ")}
    STAMP

    new_content = if existing.include?("## libpqcsb")
      # Replace existing libpqcsb section
      existing.sub(/## libpqcsb.*?(?=^##|\z)/m, pqcsb_provenance)
    else
      # Append new libpqcsb section
      existing + "\n" + pqcsb_provenance
    end

    File.write(provenance_path, new_content)
    puts "  Updated #{provenance_path}"

    Rake::Task[:"vendor_pqcsb:lock"].invoke
    puts "Done. Run `rake test` to verify."
  end

  desc "Update vendored libpqcsb files from GitHub release"
  task :update, [:version] do |_t, args|
    require "net/http"
    require "rubygems/package"
    require "zlib"
    require "stringio"
    require "fileutils"
    require "digest"

    version = args[:version] || abort("Usage: rake vendor_pqcsb:update[VERSION]  (e.g. 0.1.0)")
    tag = "v#{version}"
    prefix = "libpqcsb-#{version}"
    filename = "#{prefix}.tar.gz"
    url = "https://github.com/msuliq/libpqcsb/releases/download/#{tag}/#{filename}"

    puts "Downloading #{url} ..."
    uri = URI(url)
    response = Net::HTTP.get_response(uri)
    # Follow one redirect (GitHub releases redirect to S3)
    if response.is_a?(Net::HTTPRedirection)
      response = Net::HTTP.get_response(URI(response["location"]))
    end
    abort "Download failed: #{response.code} #{response.message}" unless response.is_a?(Net::HTTPSuccess)
    tarball = response.body

    # Verify SHA256 against the tarball checksum table if an entry exists.
    actual_sha256 = Digest::SHA256.hexdigest(tarball)
    if (expected = VENDOR_PQCSB_CHECKSUMS[version])
      abort <<~MSG unless actual_sha256 == expected
        SHA256 mismatch for #{filename}!
          expected: #{expected}
          actual:   #{actual_sha256}
        Refusing to update vendored files — the tarball may have been tampered with.
      MSG
      puts "  SHA256 verified: #{actual_sha256}"
    else
      warn <<~MSG
        WARNING: No known SHA256 for libpqcsb #{version}.
          Actual SHA256: #{actual_sha256}
        Pin this release by adding to VENDOR_PQCSB_CHECKSUMS in rakelib/vendor.rake:
          "#{version}" => "#{actual_sha256}"
      MSG
    end

    ext_dir = File.expand_path("ext/pqc_asn1", __dir__ + "/..")
    files = {
      "#{prefix}/include/pqcsb.h" => File.join(ext_dir, "pqcsb.h"),
      "#{prefix}/dist/pqcsb.c" => File.join(ext_dir, "pqcsb.c"),
      "#{prefix}/src/internal.h" => File.join(ext_dir, "internal.h")
    }

    Gem::Package::TarReader.new(Zlib::GzipReader.new(StringIO.new(tarball))) do |tar|
      tar.each do |entry|
        dest = files[entry.full_name]
        next unless dest

        FileUtils.mkdir_p(File.dirname(dest))
        File.write(dest, entry.read)
        puts "  Updated #{dest}"
        files.delete(entry.full_name)
      end
    end

    files.each_key { |missing| warn "WARNING: #{missing} not found in tarball" }

    # Write provenance stamp.
    provenance_path = File.join(ext_dir, "VENDOR_PROVENANCE")
    existing = File.exist?(provenance_path) ? File.read(provenance_path) : ""
    pqcsb_provenance = <<~STAMP
      ## libpqcsb

      upstream: https://github.com/msuliq/libpqcsb
      version: #{version}
      tag: #{tag}
      tarball_sha256: #{actual_sha256}
      vendored_at: #{Time.now.utc.strftime("%Y-%m-%dT%H:%M:%SZ")}
    STAMP

    new_content = if existing.include?("## libpqcsb")
      existing.sub(/## libpqcsb.*?(?=^##|\z)/m, pqcsb_provenance)
    else
      existing + "\n" + pqcsb_provenance
    end

    File.write(provenance_path, new_content)
    puts "  Updated #{provenance_path}"

    Rake::Task[:"vendor_pqcsb:lock"].invoke
    puts "Done. Run `rake test` to verify."
  end
end
